/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usindhexaminationsystemproject;

import Frame.*;
/**
 *
 * @author Salman Ahmed
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTlistPrint = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemFaculty = new javax.swing.JMenuItem();
        jMenuItemDepartment = new javax.swing.JMenuItem();
        jMenuItemProgram = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuScheme = new javax.swing.JMenu();
        jMenuItemScheme = new javax.swing.JMenuItem();
        jMenuItemSchemePart = new javax.swing.JMenuItem();
        jMenuItemSchemeSemester = new javax.swing.JMenuItem();
        jMenuItemSchemeDetails = new javax.swing.JMenuItem();
        jMenuStudent = new javax.swing.JMenu();
        jMenuItemStudent = new javax.swing.JMenuItem();
        jMenuItemStudentPart = new javax.swing.JMenuItem();
        jMenuSeatList = new javax.swing.JMenu();
        jMenuItemSeatList = new javax.swing.JMenuItem();
        jMenuItemSeatListDetails = new javax.swing.JMenuItem();
        jMenuLedger = new javax.swing.JMenu();
        jMenuItemLedger = new javax.swing.JMenuItem();
        jMenuItemLedgerListDetails = new javax.swing.JMenuItem();
        jMenuItemLedgerSemester = new javax.swing.JMenuItem();
        jMenuLedgerDetails = new javax.swing.JMenu();
        jMenuItemDetails = new javax.swing.JMenuItem();
        jMenuItemByCourceNo = new javax.swing.JMenuItem();
        jMenuItemLedgerSummary = new javax.swing.JMenuItem();
        jMenuItemConcArea = new javax.swing.JMenuItem();
        jMenuItemAcSchemeDetails = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel1.setText("ADMISSION SYSTEM");

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 48)); // NOI18N
        jLabel2.setText("UNIVERSITY OF SINDH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(144, 144, 144)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        BTlistPrint.setBackground(new java.awt.Color(212, 140, 1));
        BTlistPrint.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        BTlistPrint.setForeground(new java.awt.Color(255, 255, 255));
        BTlistPrint.setText("LIST PRINTING");
        BTlistPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTlistPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(138, 138, 138))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTlistPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTlistPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(278, 278, 278))
        );

        jMenu1.setText("MENU");
        jMenu1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N

        jMenuItemFaculty.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jMenuItemFaculty.setText("Faculty");
        jMenuItemFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFacultyActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFaculty);

        jMenuItemDepartment.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jMenuItemDepartment.setText("Department");
        jMenuItemDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDepartmentActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDepartment);

        jMenuItemProgram.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jMenuItemProgram.setText("Program");
        jMenuItemProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProgramActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemProgram);

        jMenuItem4.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jMenuItem4.setText("Batch");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuScheme.setText("Scheme");

        jMenuItemScheme.setText("Scheme");
        jMenuItemScheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSchemeActionPerformed(evt);
            }
        });
        jMenuScheme.add(jMenuItemScheme);

        jMenuItemSchemePart.setText("Scheme Part");
        jMenuItemSchemePart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSchemePartActionPerformed(evt);
            }
        });
        jMenuScheme.add(jMenuItemSchemePart);

        jMenuItemSchemeSemester.setText("Scheme Semester");
        jMenuItemSchemeSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSchemeSemesterActionPerformed(evt);
            }
        });
        jMenuScheme.add(jMenuItemSchemeSemester);

        jMenuItemSchemeDetails.setText("Scheme Details");
        jMenuItemSchemeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSchemeDetailsActionPerformed(evt);
            }
        });
        jMenuScheme.add(jMenuItemSchemeDetails);

        jMenu1.add(jMenuScheme);

        jMenuStudent.setText("Student");

        jMenuItemStudent.setText("Student");
        jMenuItemStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStudentActionPerformed(evt);
            }
        });
        jMenuStudent.add(jMenuItemStudent);

        jMenuItemStudentPart.setText("Student Part");
        jMenuItemStudentPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStudentPartActionPerformed(evt);
            }
        });
        jMenuStudent.add(jMenuItemStudentPart);

        jMenu1.add(jMenuStudent);

        jMenuSeatList.setText("Seat List");

        jMenuItemSeatList.setText("Seat List");
        jMenuItemSeatList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSeatListActionPerformed(evt);
            }
        });
        jMenuSeatList.add(jMenuItemSeatList);

        jMenuItemSeatListDetails.setText("Seat List Details");
        jMenuItemSeatListDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSeatListDetailsActionPerformed(evt);
            }
        });
        jMenuSeatList.add(jMenuItemSeatListDetails);

        jMenu1.add(jMenuSeatList);

        jMenuLedger.setText("Ledger");

        jMenuItemLedger.setText("Ledger");
        jMenuItemLedger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLedgerActionPerformed(evt);
            }
        });
        jMenuLedger.add(jMenuItemLedger);

        jMenuItemLedgerListDetails.setText("Ledger List Details");
        jMenuItemLedgerListDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLedgerListDetailsActionPerformed(evt);
            }
        });
        jMenuLedger.add(jMenuItemLedgerListDetails);

        jMenuItemLedgerSemester.setText("Ledger Semester");
        jMenuItemLedgerSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLedgerSemesterActionPerformed(evt);
            }
        });
        jMenuLedger.add(jMenuItemLedgerSemester);

        jMenuLedgerDetails.setText("Ledger Details");

        jMenuItemDetails.setText("Details");
        jMenuItemDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDetailsActionPerformed(evt);
            }
        });
        jMenuLedgerDetails.add(jMenuItemDetails);

        jMenuItemByCourceNo.setText("By Cource Number");
        jMenuItemByCourceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemByCourceNoActionPerformed(evt);
            }
        });
        jMenuLedgerDetails.add(jMenuItemByCourceNo);

        jMenuLedger.add(jMenuLedgerDetails);

        jMenuItemLedgerSummary.setText("Ledger Summary");
        jMenuItemLedgerSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLedgerSummaryActionPerformed(evt);
            }
        });
        jMenuLedger.add(jMenuItemLedgerSummary);

        jMenu1.add(jMenuLedger);

        jMenuItemConcArea.setText("Concentration Area");
        jMenuItemConcArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConcAreaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemConcArea);

        jMenuItemAcSchemeDetails.setText("AC Scheme Details");
        jMenuItemAcSchemeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcSchemeDetailsActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAcSchemeDetails);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFacultyActionPerformed
       // new FacultyFrame().setVisible(true);
        
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jMenuItemFacultyActionPerformed

    private void jMenuItemDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDepartmentActionPerformed
       // new DepartmentFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDepartmentActionPerformed

    private void jMenuItemProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProgramActionPerformed
      //  new ProgramFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemProgramActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        //new BatchFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemSchemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSchemeActionPerformed
       // new SchemeFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSchemeActionPerformed

    private void jMenuItemSchemePartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSchemePartActionPerformed
        //new SchemePartFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSchemePartActionPerformed

    private void jMenuItemSchemeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSchemeDetailsActionPerformed
       // new SchemeDetailsFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSchemeDetailsActionPerformed

    private void jMenuItemSchemeSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSchemeSemesterActionPerformed
       // new SchemeSemesterFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSchemeSemesterActionPerformed

    private void jMenuItemStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStudentActionPerformed
       // new StudentFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemStudentActionPerformed

    private void jMenuItemStudentPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStudentPartActionPerformed
       // new StudentPartFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemStudentPartActionPerformed

    private void jMenuItemSeatListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSeatListActionPerformed
       // new SeatListFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSeatListActionPerformed

    private void jMenuItemSeatListDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSeatListDetailsActionPerformed
       // new SeatListDetailsFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSeatListDetailsActionPerformed

    private void jMenuItemLedgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLedgerActionPerformed
        new LedgerFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemLedgerActionPerformed

    private void jMenuItemLedgerListDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLedgerListDetailsActionPerformed
       // new LedgerListDetailFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemLedgerListDetailsActionPerformed

    private void jMenuItemLedgerSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLedgerSemesterActionPerformed
       // new LedgerSemesterFrame().setVisible(rootPaneCheckingEnabled);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemLedgerSemesterActionPerformed

    private void jMenuItemDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDetailsActionPerformed
       // new LedgerDetailsFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDetailsActionPerformed

    private void jMenuItemByCourceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemByCourceNoActionPerformed
       // new LedgerDetailsCourceNoFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemByCourceNoActionPerformed

    private void jMenuItemLedgerSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLedgerSummaryActionPerformed
        new LedgerDetailsSummaryFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemLedgerSummaryActionPerformed

    private void jMenuItemConcAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConcAreaActionPerformed
       // new ConcAreaFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemConcAreaActionPerformed

    private void jMenuItemAcSchemeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcSchemeDetailsActionPerformed
       // new AcSchemeDetailsFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAcSchemeDetailsActionPerformed

    private void BTlistPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTlistPrintActionPerformed
        try{
            new Printing();
        }catch(Exception ee){
            ee.printStackTrace();
            CustomClassess.MainWorkPlace.Jpane("Printing ERROR "+ee.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BTlistPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTlistPrint;
    private javax.swing.JButton BTprint;
    private javax.swing.JButton BTprint1;
    private javax.swing.JButton BTprint2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAcSchemeDetails;
    private javax.swing.JMenuItem jMenuItemByCourceNo;
    private javax.swing.JMenuItem jMenuItemConcArea;
    private javax.swing.JMenuItem jMenuItemDepartment;
    private javax.swing.JMenuItem jMenuItemDetails;
    private javax.swing.JMenuItem jMenuItemFaculty;
    private javax.swing.JMenuItem jMenuItemLedger;
    private javax.swing.JMenuItem jMenuItemLedgerListDetails;
    private javax.swing.JMenuItem jMenuItemLedgerSemester;
    private javax.swing.JMenuItem jMenuItemLedgerSummary;
    private javax.swing.JMenuItem jMenuItemProgram;
    private javax.swing.JMenuItem jMenuItemScheme;
    private javax.swing.JMenuItem jMenuItemSchemeDetails;
    private javax.swing.JMenuItem jMenuItemSchemePart;
    private javax.swing.JMenuItem jMenuItemSchemeSemester;
    private javax.swing.JMenuItem jMenuItemSeatList;
    private javax.swing.JMenuItem jMenuItemSeatListDetails;
    private javax.swing.JMenuItem jMenuItemStudent;
    private javax.swing.JMenuItem jMenuItemStudentPart;
    private javax.swing.JMenu jMenuLedger;
    private javax.swing.JMenu jMenuLedgerDetails;
    private javax.swing.JMenu jMenuScheme;
    private javax.swing.JMenu jMenuSeatList;
    private javax.swing.JMenu jMenuStudent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
